### ISSUE TITLE
unfinished paragraph in London-school

### ISSUE THREAD

**Issue by mbjelac** [testdouble/contributing-tests#3]
In https://github.com/testdouble/contributing-tests/wiki/London-school-TDD, the last chapter `Increased refactoring cost`, the second paragraph has an unfinished sentence: `In general, attempting to refactor the implementation without changing the test first`

**Comment by rosston** [comment]
Good catch! I'm not sure what the rest of the sentence was intended to be, but I did find [the change where it was introduced](https://github.com/testdouble/contributing-tests/wiki/London-school-TDD/_compare/2b6c900ef66e6df136e9cfc58a2a7d08aef913bc...b1e7051beda1f31dd46909906dc056c5e25393e5) (revision b1e7051). Maybe @searls can provide more insight since he was the author of this change/doc?

**Comment by searls** [comment]
LOL, can one of you send a PR to finish my sentences for me?

I think it should just be deleted—short of remembering what I was thinking years ago

**Comment by rosston** [comment]
Deleted!
